version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: picture
      WORDPRESS_DB_PASSWORD: p@ssword
      WORDPRESS_DB_NAME: picture
    volumes:
      - wordpress:/var/www/html
      - ./picture:/var/www/html/wp-content/themes/picture
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: picture
      MYSQL_USER: picture
      MYSQL_PASSWORD: p@ssword
      MYSQL_RANDOM_ROOT_PASSWORD: p@ssword
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: